#= require ./store
#= require_tree ./addons
#= require_tree ./mixins
#= require_tree ./translations
#= require_tree ./models
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./components
#= require_tree ./helpers
#= require_tree ./templates
#= require_tree ./routes
#= require ./router
#= require_self
